
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace AddChanellDialog {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class AddChanellDialog : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label label_Name_TGChannelName;
        
        private Terminal.Gui.TextField textField_tgchannel_name;
        
        private Terminal.Gui.Label label_Name_SyncWD;
        
        private Terminal.Gui.CheckBox checkBox_WD_sunday;
        
        private Terminal.Gui.CheckBox checkBox_WD_monday;
        
        private Terminal.Gui.CheckBox checkBox_WD_tuesday;
        
        private Terminal.Gui.CheckBox checkBox_WD_wednesday;
        
        private Terminal.Gui.CheckBox checkBox_WD_thursday;
        
        private Terminal.Gui.CheckBox checkBox_WD_friday;
        
        private Terminal.Gui.CheckBox checkBox_WD_saturday;
        
        private Terminal.Gui.Label label_Name_SyncTime;
        
        private Terminal.Gui.TimeField timeField;
        
        private Terminal.Gui.Button buttonAdd;
        
        private Terminal.Gui.Button buttonCancel;
        
        private void InitializeComponent() {
            this.buttonCancel = new Terminal.Gui.Button();
            this.buttonAdd = new Terminal.Gui.Button();
            this.timeField = new Terminal.Gui.TimeField();
            this.label_Name_SyncTime = new Terminal.Gui.Label();
            this.checkBox_WD_saturday = new Terminal.Gui.CheckBox();
            this.checkBox_WD_friday = new Terminal.Gui.CheckBox();
            this.checkBox_WD_thursday = new Terminal.Gui.CheckBox();
            this.checkBox_WD_wednesday = new Terminal.Gui.CheckBox();
            this.checkBox_WD_tuesday = new Terminal.Gui.CheckBox();
            this.checkBox_WD_monday = new Terminal.Gui.CheckBox();
            this.checkBox_WD_sunday = new Terminal.Gui.CheckBox();
            this.label_Name_SyncWD = new Terminal.Gui.Label();
            this.textField_tgchannel_name = new Terminal.Gui.TextField();
            this.label_Name_TGChannelName = new Terminal.Gui.Label();
            this.Width = Dim.Auto();
            this.Height = Dim.Auto();
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Movable;
            this.Modal = true;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this.label_Name_TGChannelName.Width = Dim.Auto();
            this.label_Name_TGChannelName.Height = 1;
            this.label_Name_TGChannelName.X = 0;
            this.label_Name_TGChannelName.Y = 1;
            this.label_Name_TGChannelName.Visible = true;
            this.label_Name_TGChannelName.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label_Name_TGChannelName.Data = "label_Name_TGChannelName";
            this.label_Name_TGChannelName.Text = "TG Channel name:";
            this.label_Name_TGChannelName.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label_Name_TGChannelName);
            this.textField_tgchannel_name.Width = 28;
            this.textField_tgchannel_name.Height = 1;
            this.textField_tgchannel_name.X = 17;
            this.textField_tgchannel_name.Y = 1;
            this.textField_tgchannel_name.Visible = true;
            this.textField_tgchannel_name.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.textField_tgchannel_name.Secret = false;
            this.textField_tgchannel_name.Data = "textField_tgchannel_name";
            this.textField_tgchannel_name.Text = "Input TG channel @name or ID";
            this.textField_tgchannel_name.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.textField_tgchannel_name);
            this.label_Name_SyncWD.Width = Dim.Auto();
            this.label_Name_SyncWD.Height = 1;
            this.label_Name_SyncWD.X = 0;
            this.label_Name_SyncWD.Y = 4;
            this.label_Name_SyncWD.Visible = true;
            this.label_Name_SyncWD.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label_Name_SyncWD.Data = "label_Name_SyncWD";
            this.label_Name_SyncWD.Text = "Sync WeekDay:";
            this.label_Name_SyncWD.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label_Name_SyncWD);
            this.checkBox_WD_sunday.Width = Dim.Auto();
            this.checkBox_WD_sunday.Height = 1;
            this.checkBox_WD_sunday.X = 14;
            this.checkBox_WD_sunday.Y = 4;
            this.checkBox_WD_sunday.Visible = true;
            this.checkBox_WD_sunday.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_WD_sunday.Data = "checkBox_WD_sunday";
            this.checkBox_WD_sunday.Text = "Sunday";
            this.checkBox_WD_sunday.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_WD_sunday.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_WD_sunday);
            this.checkBox_WD_monday.Width = Dim.Auto();
            this.checkBox_WD_monday.Height = 1;
            this.checkBox_WD_monday.X = 14;
            this.checkBox_WD_monday.Y = 5;
            this.checkBox_WD_monday.Visible = true;
            this.checkBox_WD_monday.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_WD_monday.Data = "checkBox_WD_monday";
            this.checkBox_WD_monday.Text = "Monday";
            this.checkBox_WD_monday.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_WD_monday.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_WD_monday);
            this.checkBox_WD_tuesday.Width = Dim.Auto();
            this.checkBox_WD_tuesday.Height = 1;
            this.checkBox_WD_tuesday.X = 14;
            this.checkBox_WD_tuesday.Y = 6;
            this.checkBox_WD_tuesday.Visible = true;
            this.checkBox_WD_tuesday.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_WD_tuesday.Data = "checkBox_WD_tuesday";
            this.checkBox_WD_tuesday.Text = "Tuesday";
            this.checkBox_WD_tuesday.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_WD_tuesday.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_WD_tuesday);
            this.checkBox_WD_wednesday.Width = Dim.Auto();
            this.checkBox_WD_wednesday.Height = 1;
            this.checkBox_WD_wednesday.X = 14;
            this.checkBox_WD_wednesday.Y = 7;
            this.checkBox_WD_wednesday.Visible = true;
            this.checkBox_WD_wednesday.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_WD_wednesday.Data = "checkBox_WD_wednesday";
            this.checkBox_WD_wednesday.Text = "Wednesday";
            this.checkBox_WD_wednesday.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_WD_wednesday.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_WD_wednesday);
            this.checkBox_WD_thursday.Width = Dim.Auto();
            this.checkBox_WD_thursday.Height = 1;
            this.checkBox_WD_thursday.X = 14;
            this.checkBox_WD_thursday.Y = 8;
            this.checkBox_WD_thursday.Visible = true;
            this.checkBox_WD_thursday.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_WD_thursday.Data = "checkBox_WD_thursday";
            this.checkBox_WD_thursday.Text = "Thursday";
            this.checkBox_WD_thursday.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_WD_thursday.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_WD_thursday);
            this.checkBox_WD_friday.Width = Dim.Auto();
            this.checkBox_WD_friday.Height = 1;
            this.checkBox_WD_friday.X = 14;
            this.checkBox_WD_friday.Y = 9;
            this.checkBox_WD_friday.Visible = true;
            this.checkBox_WD_friday.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_WD_friday.Data = "checkBox_WD_friday";
            this.checkBox_WD_friday.Text = "Friday";
            this.checkBox_WD_friday.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_WD_friday.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_WD_friday);
            this.checkBox_WD_saturday.Width = Dim.Auto();
            this.checkBox_WD_saturday.Height = 1;
            this.checkBox_WD_saturday.X = 14;
            this.checkBox_WD_saturday.Y = 10;
            this.checkBox_WD_saturday.Visible = true;
            this.checkBox_WD_saturday.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_WD_saturday.Data = "checkBox_WD_saturday";
            this.checkBox_WD_saturday.Text = "Saturday";
            this.checkBox_WD_saturday.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_WD_saturday.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_WD_saturday);
            this.label_Name_SyncTime.Width = Dim.Auto();
            this.label_Name_SyncTime.Height = 1;
            this.label_Name_SyncTime.X = 0;
            this.label_Name_SyncTime.Y = 12;
            this.label_Name_SyncTime.Visible = true;
            this.label_Name_SyncTime.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label_Name_SyncTime.Data = "label_Name_SyncTime";
            this.label_Name_SyncTime.Text = "Sync time:";
            this.label_Name_SyncTime.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label_Name_SyncTime);
            this.timeField.Width = 10;
            this.timeField.Height = 1;
            this.timeField.X = 14;
            this.timeField.Y = 12;
            this.timeField.Visible = true;
            this.timeField.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.timeField.Secret = false;
            this.timeField.Data = "timeField";
            this.timeField.Text = " 00:00:01";
            this.timeField.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.timeField);
            this.buttonAdd.Width = Dim.Auto();
            this.buttonAdd.Height = 1;
            this.buttonAdd.X = 0;
            this.buttonAdd.Y = 15;
            this.buttonAdd.Visible = true;
            this.buttonAdd.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.buttonAdd.Data = "buttonAdd";
            this.buttonAdd.Text = "Add";
            this.buttonAdd.TextAlignment = Terminal.Gui.Alignment.Center;
            this.buttonAdd.IsDefault = false;
            this.Add(this.buttonAdd);
            this.buttonCancel.Width = Dim.Auto();
            this.buttonCancel.Height = 1;
            this.buttonCancel.X = 32;
            this.buttonCancel.Y = 15;
            this.buttonCancel.Visible = true;
            this.buttonCancel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.buttonCancel.Data = "buttonCancel";
            this.buttonCancel.Text = "Cancel";
            this.buttonCancel.TextAlignment = Terminal.Gui.Alignment.Center;
            this.buttonCancel.IsDefault = true;
            this.Add(this.buttonCancel);
        }
    }
}
