
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Class_AddChennel {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class AddChennel : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label_Name_ChanelId;
        
        private Terminal.Gui.TextField textField;
        
        private Terminal.Gui.Label label_Name_WeekDay;
        
        private Terminal.Gui.CheckBox checkBox_syncWeekDay_Sun;
        
        private Terminal.Gui.CheckBox checkBox_syncWeekDay_Mon;
        
        private Terminal.Gui.CheckBox checkBox_syncWeekDay_Tue;
        
        private Terminal.Gui.CheckBox checkBox_syncWeekDay_Wed;
        
        private Terminal.Gui.CheckBox checkBox_syncWeekDay_Thu;
        
        private Terminal.Gui.CheckBox checkBox_syncWeekDay_Fri;
        
        private Terminal.Gui.CheckBox checkBox_syncWeekDay_Sat;
        
        private Terminal.Gui.Label label_name_time;
        
        private Terminal.Gui.TimeField timeField;
        
        private Terminal.Gui.Button button_Add;
        
        private Terminal.Gui.Button buttonCancel;
        
        private void InitializeComponent() {
            this.buttonCancel = new Terminal.Gui.Button();
            this.button_Add = new Terminal.Gui.Button();
            this.timeField = new Terminal.Gui.TimeField();
            this.label_name_time = new Terminal.Gui.Label();
            this.checkBox_syncWeekDay_Sat = new Terminal.Gui.CheckBox();
            this.checkBox_syncWeekDay_Fri = new Terminal.Gui.CheckBox();
            this.checkBox_syncWeekDay_Thu = new Terminal.Gui.CheckBox();
            this.checkBox_syncWeekDay_Wed = new Terminal.Gui.CheckBox();
            this.checkBox_syncWeekDay_Tue = new Terminal.Gui.CheckBox();
            this.checkBox_syncWeekDay_Mon = new Terminal.Gui.CheckBox();
            this.checkBox_syncWeekDay_Sun = new Terminal.Gui.CheckBox();
            this.label_Name_WeekDay = new Terminal.Gui.Label();
            this.textField = new Terminal.Gui.TextField();
            this.label_Name_ChanelId = new Terminal.Gui.Label();
            this.Width = Dim.Auto();
            this.Height = Dim.Auto();
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this.label_Name_ChanelId.Width = Dim.Auto();
            this.label_Name_ChanelId.Height = 1;
            this.label_Name_ChanelId.X = 0;
            this.label_Name_ChanelId.Y = 0;
            this.label_Name_ChanelId.Visible = true;
            this.label_Name_ChanelId.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label_Name_ChanelId.Data = "label_Name_ChanelId";
            this.label_Name_ChanelId.Text = "TG Chanel ID:";
            this.label_Name_ChanelId.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label_Name_ChanelId);
            this.textField.Width = 28;
            this.textField.Height = 1;
            this.textField.X = 14;
            this.textField.Y = 0;
            this.textField.Visible = true;
            this.textField.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "Input @channelName or ID";
            this.textField.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.textField);
            this.label_Name_WeekDay.Width = Dim.Auto();
            this.label_Name_WeekDay.Height = 1;
            this.label_Name_WeekDay.X = 0;
            this.label_Name_WeekDay.Y = 2;
            this.label_Name_WeekDay.Visible = true;
            this.label_Name_WeekDay.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label_Name_WeekDay.Data = "label_Name_WeekDay";
            this.label_Name_WeekDay.Text = "Sync WeekDay:";
            this.label_Name_WeekDay.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label_Name_WeekDay);
            this.checkBox_syncWeekDay_Sun.Width = Dim.Auto();
            this.checkBox_syncWeekDay_Sun.Height = 1;
            this.checkBox_syncWeekDay_Sun.X = 14;
            this.checkBox_syncWeekDay_Sun.Y = 2;
            this.checkBox_syncWeekDay_Sun.Visible = true;
            this.checkBox_syncWeekDay_Sun.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_syncWeekDay_Sun.Data = "checkBox_syncWeekDay_Sun";
            this.checkBox_syncWeekDay_Sun.Text = "Sunday";
            this.checkBox_syncWeekDay_Sun.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_syncWeekDay_Sun.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_syncWeekDay_Sun);
            this.checkBox_syncWeekDay_Mon.Width = Dim.Auto();
            this.checkBox_syncWeekDay_Mon.Height = 1;
            this.checkBox_syncWeekDay_Mon.X = 14;
            this.checkBox_syncWeekDay_Mon.Y = 3;
            this.checkBox_syncWeekDay_Mon.Visible = true;
            this.checkBox_syncWeekDay_Mon.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_syncWeekDay_Mon.Data = "checkBox_syncWeekDay_Mon";
            this.checkBox_syncWeekDay_Mon.Text = "Monday";
            this.checkBox_syncWeekDay_Mon.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_syncWeekDay_Mon.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_syncWeekDay_Mon);
            this.checkBox_syncWeekDay_Tue.Width = Dim.Auto();
            this.checkBox_syncWeekDay_Tue.Height = 1;
            this.checkBox_syncWeekDay_Tue.X = 14;
            this.checkBox_syncWeekDay_Tue.Y = 4;
            this.checkBox_syncWeekDay_Tue.Visible = true;
            this.checkBox_syncWeekDay_Tue.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_syncWeekDay_Tue.Data = "checkBox_syncWeekDay_Tue";
            this.checkBox_syncWeekDay_Tue.Text = "Tuesday";
            this.checkBox_syncWeekDay_Tue.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_syncWeekDay_Tue.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_syncWeekDay_Tue);
            this.checkBox_syncWeekDay_Wed.Width = Dim.Auto();
            this.checkBox_syncWeekDay_Wed.Height = 1;
            this.checkBox_syncWeekDay_Wed.X = 14;
            this.checkBox_syncWeekDay_Wed.Y = 5;
            this.checkBox_syncWeekDay_Wed.Visible = true;
            this.checkBox_syncWeekDay_Wed.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_syncWeekDay_Wed.Data = "checkBox_syncWeekDay_Wed";
            this.checkBox_syncWeekDay_Wed.Text = "Wednesday";
            this.checkBox_syncWeekDay_Wed.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_syncWeekDay_Wed.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_syncWeekDay_Wed);
            this.checkBox_syncWeekDay_Thu.Width = Dim.Auto();
            this.checkBox_syncWeekDay_Thu.Height = 1;
            this.checkBox_syncWeekDay_Thu.X = 14;
            this.checkBox_syncWeekDay_Thu.Y = 6;
            this.checkBox_syncWeekDay_Thu.Visible = true;
            this.checkBox_syncWeekDay_Thu.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_syncWeekDay_Thu.Data = "checkBox_syncWeekDay_Thu";
            this.checkBox_syncWeekDay_Thu.Text = "Thursday";
            this.checkBox_syncWeekDay_Thu.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_syncWeekDay_Thu.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_syncWeekDay_Thu);
            this.checkBox_syncWeekDay_Fri.Width = Dim.Auto();
            this.checkBox_syncWeekDay_Fri.Height = 1;
            this.checkBox_syncWeekDay_Fri.X = 14;
            this.checkBox_syncWeekDay_Fri.Y = 7;
            this.checkBox_syncWeekDay_Fri.Visible = true;
            this.checkBox_syncWeekDay_Fri.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_syncWeekDay_Fri.Data = "checkBox_syncWeekDay_Fri";
            this.checkBox_syncWeekDay_Fri.Text = "Friday";
            this.checkBox_syncWeekDay_Fri.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_syncWeekDay_Fri.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_syncWeekDay_Fri);
            this.checkBox_syncWeekDay_Sat.Width = Dim.Auto();
            this.checkBox_syncWeekDay_Sat.Height = 1;
            this.checkBox_syncWeekDay_Sat.X = 14;
            this.checkBox_syncWeekDay_Sat.Y = 8;
            this.checkBox_syncWeekDay_Sat.Visible = true;
            this.checkBox_syncWeekDay_Sat.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.checkBox_syncWeekDay_Sat.Data = "checkBox_syncWeekDay_Sat";
            this.checkBox_syncWeekDay_Sat.Text = "Saturday";
            this.checkBox_syncWeekDay_Sat.TextAlignment = Terminal.Gui.Alignment.Start;
            this.checkBox_syncWeekDay_Sat.CheckedState = Terminal.Gui.CheckState.UnChecked;
            this.Add(this.checkBox_syncWeekDay_Sat);
            this.label_name_time.Width = Dim.Auto();
            this.label_name_time.Height = 1;
            this.label_name_time.X = 0;
            this.label_name_time.Y = 10;
            this.label_name_time.Visible = true;
            this.label_name_time.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label_name_time.Data = "label_name_time";
            this.label_name_time.Text = "Sync time:";
            this.label_name_time.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label_name_time);
            this.timeField.Width = 10;
            this.timeField.Height = 1;
            this.timeField.X = 14;
            this.timeField.Y = 10;
            this.timeField.Visible = true;
            this.timeField.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.timeField.Secret = false;
            this.timeField.Data = "timeField";
            this.timeField.Text = " 02:48:05";
            this.timeField.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.timeField);
            this.button_Add.Width = Dim.Auto();
            this.button_Add.Height = 1;
            this.button_Add.X = 0;
            this.button_Add.Y = 12;
            this.button_Add.Visible = true;
            this.button_Add.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.button_Add.Data = "button_Add";
            this.button_Add.Text = "Add";
            this.button_Add.TextAlignment = Terminal.Gui.Alignment.Center;
            this.button_Add.IsDefault = false;
            this.Add(this.button_Add);
            this.buttonCancel.Width = Dim.Auto();
            this.buttonCancel.Height = 1;
            this.buttonCancel.X = 34;
            this.buttonCancel.Y = 12;
            this.buttonCancel.Visible = true;
            this.buttonCancel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.buttonCancel.Data = "buttonCancel";
            this.buttonCancel.Text = "Cancel";
            this.buttonCancel.TextAlignment = Terminal.Gui.Alignment.Center;
            this.buttonCancel.IsDefault = false;
            this.Add(this.buttonCancel);
        }
    }
}
